# permissions for end users to view widgetprocessors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: widgetprocessor-viewer-role
rules:
- apiGroups:
  - widget.redhat-demo.com
  resources:
  - widgetprocessors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - widget.redhat-demo.com
  resources:
  - widgetprocessors/status
  verbs:
  - get
