# permissions for end users to edit widgetprocessors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: widgetprocessor-editor-role
rules:
- apiGroups:
  - widget.redhat-demo.com
  resources:
  - widgetprocessors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - widget.redhat-demo.com
  resources:
  - widgetprocessors/status
  verbs:
  - get
